<a href="https://colab.research.google.com/github/Vinothini12b/Python-Data-Analysis-Projects/blob/main/Vinothini_ShoppingStop.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


**Task 1:**

Import Pandas Library and create a dataframe named "salesdata" from a given URL and then print it. URL - https://raw.githubusercontent.com/Invact-Abhay/DOE11/main/GlobalSales%20Data.csv

In [ ]:
import pandas as pd
salesdata=pd.read_csv("https://raw.githubusercontent.com/Invact-Abhay/DOE11/main/GlobalSales%20Data.csv")
salesdata

,TransactionID,Month,Date,ProductCategory,ProductName,UnitsSold,UnitPrice,TotalRevenue,Region,PaymentMethod
0,10001,Jan,1/1/2024,Electronics,iPhone 14 Pro,2,79999,159998.40,North America,Credit Card
1,10002,Jan,1/2/2024,Home Appliances,Dyson V11 Vacuum,1,39999,499.99,Europe,PayPal
2,10003,Jan,1/3/2024,Clothing,Levi's 501 Jeans,3,5599,209.97,Asia,Debit Card
3,10004,Jan,1/4/2024,Books,The Da Vinci Code,4,1279,63.96,North America,Credit Card
4,10005,Jan,1/5/2024,Beauty Products,Neutrogena Skincare Set,1,7199,89.99,Europe,PayPal
...,...,...,...,...,...,...,...,...,...,...
235,10236,Aug,8/23/2024,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,12799,159.99,Europe,PayPal
236,10237,Aug,8/24/2024,Clothing,Nike Air Force 1 Sneakers,3,7200,270.00,Asia,Debit Card
237,10238,Aug,8/25/2024,Books,The Handmaid's Tale by Margaret Atwood,3,879,32.97,North America,Credit Card
238,10239,Aug,8/26/2024,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,4400,55.00,Europe,PayPal
239,10240,Aug,8/27/2024,Sports,Yeti Rambler 20 oz Tumbler,2,2399,59.98,Asia,Credit Card

**Task 2:**

Sort the dataframe  by arranging

"Region" column in descending order

then "ProductCategory" column in ascending order.

In [ ]:
salesdata.sort_values(by=["Region","ProductCategory"],ascending=[False,True])

,TransactionID,Month,Date,ProductCategory,ProductName,UnitsSold,UnitPrice,TotalRevenue,Region,PaymentMethod
3,10004,Jan,1/4/2024,Books,The Da Vinci Code,4,1279,63.96,North America,Credit Card
9,10010,Jan,1/10/2024,Books,Dune by Frank Herbert,2,2079,51.98,North America,Credit Card
15,10016,Jan,1/16/2024,Books,"Salt, Fat, Acid, Heat by Samin Nosrat",3,2879,107.97,North America,Credit Card
21,10022,Jan,1/22/2024,Books,Gone Girl by Gillian Flynn,2,1839,45.98,North America,Credit Card
27,10028,Jan,1/28/2024,Books,Pride and Prejudice by Jane Austen,3,1039,38.97,North America,Credit Card
...,...,...,...,...,...,...,...,...,...,...
215,10216,Aug,8/3/2024,Sports,YETI Tundra 65 Cooler,1,27999,349.99,Asia,Credit Card
221,10222,Aug,8/9/2024,Sports,Garmin Forerunner 945,1,47999,599.99,Asia,Credit Card
227,10228,Aug,8/15/2024,Sports,Fitbit Luxe,2,11996,299.90,Asia,Credit Card
233,10234,Aug,8/21/2024,Sports,Hydro Flask Standard Mouth Water Bottle,3,2636,98.85,Asia,Credit Card
239,10240,Aug,8/27/2024,Sports,Yeti Rambler 20 oz Tumbler,2,2399,59.98,Asia,Credit Card

**Task 3:**

Sort the dataframe  by arranging

"ProductName" column in ascending order

then "Region" column in ascending order

In [ ]:
salesdata.sort_values(by=["ProductName","Region"],ascending=[True,True])

,TransactionID,Month,Date,ProductCategory,ProductName,UnitsSold,UnitPrice,TotalRevenue,Region,PaymentMethod
33,10034,Feb,2/3/2024,Books,1984 by George Orwell,4,1599,79.96,North America,Credit Card
164,10165,June,6/13/2024,Clothing,Adidas 3-Stripes Shorts,5,2399,149.95,Asia,Debit Card
140,10141,May,5/20/2024,Clothing,Adidas Essential Track Pants,3,3599,134.97,Asia,Debit Card
23,10024,Jan,1/24/2024,Sports,Adidas FIFA World Cup Football,3,2399,89.97,Asia,Credit Card
92,10093,Apr,4/2/2024,Clothing,Adidas Originals Superstar Sneakers,4,6399,319.96,Asia,Debit Card
...,...,...,...,...,...,...,...,...,...,...
203,10204,July,7/22/2024,Sports,Yeti Tundra Haul Portable Wheeled Cooler,1,31999,399.99,Asia,Credit Card
160,10161,June,6/9/2024,Beauty Products,Youth to the People Superfood Antioxidant Clea...,1,2880,36.00,Europe,PayPal
20,10021,Jan,1/21/2024,Clothing,Zara Summer Dress,3,4799,179.97,Asia,Debit Card
0,10001,Jan,1/1/2024,Electronics,iPhone 14 Pro,2,79999,159998.40,North America,Credit Card
217,10218,Aug,8/5/2024,Home Appliances,iRobot Braava Jet M6,1,35999,449.99,Europe,PayPal

**Task 4:**

Filter the dataframe  for

ProductCategory - "Books" and "Clothing"

Sort the dataframe  by arranging

"ProductCategory" column in ascending order

then "UnitsSold" column in descending order

In [ ]:
salesdata.query('ProductCategory==["Books","Clothing"]').sort_values(["ProductCategory", "UnitsSold"],ascending=[True,False])

,TransactionID,Month,Date,ProductCategory,ProductName,UnitsSold,UnitPrice,TotalRevenue,Region,PaymentMethod
3,10004,Jan,1/4/2024,Books,The Da Vinci Code,4,1279,63.96,North America,Credit Card
33,10034,Feb,2/3/2024,Books,1984 by George Orwell,4,1599,79.96,North America,Credit Card
45,10046,Feb,2/15/2024,Books,Becoming by Michelle Obama,4,2600,130.00,North America,Credit Card
63,10064,Mar,3/4/2024,Books,Where the Crawdads Sing by Delia Owens,4,1519,75.96,North America,Credit Card
75,10076,Mar,3/16/2024,Books,To Kill a Mockingbird by Harper Lee,4,1199,59.96,North America,Credit Card
...,...,...,...,...,...,...,...,...,...,...
80,10081,Mar,3/21/2024,Clothing,Levi's Trucker Jacket,2,7199,179.98,Asia,Debit Card
146,10147,May,5/26/2024,Clothing,Levi's Sherpa Trucker Jacket,2,7840,196.00,Asia,Debit Card
194,10195,July,7/13/2024,Clothing,Adidas Ultraboost Running Shoes,2,14399,359.98,Asia,Debit Card
206,10207,July,7/25/2024,Clothing,Lululemon Wunder Under High-Rise Leggings,2,7840,196.00,Asia,Debit Card
224,10225,Aug,8/12/2024,Clothing,Old Navy Mid-Rise Rockstar Super Skinny Jeans,2,3599,89.98,Asia,Debit Card

**Task 5:**

Filter the dataframe  for

For the Month - "July"

and TotalRevenue less than 100.

In [ ]:
salesdata.query("Month=='July' and TotalRevenue<100")

,TransactionID,Month,Date,ProductCategory,ProductName,UnitsSold,UnitPrice,TotalRevenue,Region,PaymentMethod
183,10184,July,7/2/2024,Books,The Martian by Andy Weir,2,1039,25.98,North America,Credit Card
189,10190,July,7/8/2024,Books,The Catcher in the Rye by J.D. Salinger,3,879,32.97,North America,Credit Card
190,10191,July,7/9/2024,Beauty Products,Glossier Cloud Paint,1,1440,18.00,Europe,PayPal
195,10196,July,7/14/2024,Books,The Road by Cormac McCarthy,2,959,23.98,North America,Credit Card
199,10200,July,7/18/2024,Home Appliances,Instant Pot Duo Nova,1,7996,99.95,Europe,PayPal
201,10202,July,7/20/2024,Books,The Goldfinch by Donna Tartt,2,1199,29.98,North America,Credit Card
202,10203,July,7/21/2024,Beauty Products,Dr. Jart+ Cicapair Tiger Grass Color Correctin...,1,4160,52.00,Europe,PayPal
207,10208,July,7/26/2024,Books,The Great Alone by Kristin Hannah,3,1359,50.97,North America,Credit Card
208,10209,July,7/27/2024,Beauty Products,Caudalie Vinoperfect Radiance Serum,1,6320,79.00,Europe,PayPal
212,10213,July,7/31/2024,Clothing,Uniqlo Airism Seamless Boxer Briefs,4,792,39.60,Asia,Debit Card

**Task 6:**

Filter the dataframe

For the Month - "July"

and TotalRevenue less than average revenue.

In [ ]:
salesdata.query("Month=='July' and TotalRevenue<TotalRevenue.mean()")

,TransactionID,Month,Date,ProductCategory,ProductName,UnitsSold,UnitPrice,TotalRevenue,Region,PaymentMethod
182,10183,July,7/1/2024,Clothing,Levi's 511 Slim Fit Jeans,3,4799,179.97,Asia,Debit Card
183,10184,July,7/2/2024,Books,The Martian by Andy Weir,2,1039,25.98,North America,Credit Card
184,10185,July,7/3/2024,Beauty Products,La Mer Crème de la Mer Moisturizer,1,15200,190.00,Europe,PayPal
185,10186,July,7/4/2024,Sports,Polar Vantage V2,1,39996,499.95,Asia,Credit Card
186,10187,July,7/5/2024,Electronics,Sonos Beam Soundbar,1,31920,399.00,North America,Credit Card
187,10188,July,7/6/2024,Home Appliances,Anova Precision Cooker,2,15920,398.00,Europe,PayPal
188,10189,July,7/7/2024,Clothing,Nike Dri-FIT Training Shorts,4,2799,139.96,Asia,Debit Card
189,10190,July,7/8/2024,Books,The Catcher in the Rye by J.D. Salinger,3,879,32.97,North America,Credit Card
190,10191,July,7/9/2024,Beauty Products,Glossier Cloud Paint,1,1440,18.00,Europe,PayPal
191,10192,July,7/10/2024,Sports,TRX All-in-One Suspension Training System,1,13596,169.95,Asia,Credit Card
192,10193,July,7/11/2024,Electronics,Logitech G Pro X Wireless Gaming Headset,1,15999,199.99,North America,Credit Card
193,10194,July,7/12/2024,Home Appliances,Breville Smart Coffee Grinder Pro,1,15996,199.95,Europe,PayPal
194,10195,July,7/13/2024,Clothing,Adidas Ultraboost Running Shoes,2,14399,359.98,Asia,Debit Card
195,10196,July,7/14/2024,Books,The Road by Cormac McCarthy,2,959,23.98,North America,Credit Card
196,10197,July,7/15/2024,Beauty Products,Tom Ford Black Orchid Perfume,1,10000,125.00,Europe,PayPal
197,10198,July,7/16/2024,Sports,GoPro HERO9 Black,1,35999,449.99,Asia,Credit Card
198,10199,July,7/17/2024,Electronics,Apple TV 4K,2,14320,358.00,North America,Credit Card
199,10200,July,7/18/2024,Home Appliances,Instant Pot Duo Nova,1,7996,99.95,Europe,PayPal
200,10201,July,7/19/2024,Clothing,Gap 1969 Original Fit Jeans,3,4799,179.97,Asia,Debit Card
201,10202,July,7/20/2024,Books,The Goldfinch by Donna Tartt,2,1199,29.98,North America,Credit Card
202,10203,July,7/21/2024,Beauty Products,Dr. Jart+ Cicapair Tiger Grass Color Correctin...,1,4160,52.00,Europe,PayPal
203,10204,July,7/22/2024,Sports,Yeti Tundra Haul Portable Wheeled Cooler,1,31999,399.99,Asia,Credit Card
204,10205,July,7/23/2024,Electronics,Samsung Galaxy Watch 4,1,23999,299.99,North America,Credit Card
205,10206,July,7/24/2024,Home Appliances,KitchenAid Stand Mixer,1,30399,379.99,Europe,PayPal
206,10207,July,7/25/2024,Clothing,Lululemon Wunder Under High-Rise Leggings,2,7840,196.00,Asia,Debit Card
207,10208,July,7/26/2024,Books,The Great Alone by Kristin Hannah,3,1359,50.97,North America,Credit Card
208,10209,July,7/27/2024,Beauty Products,Caudalie Vinoperfect Radiance Serum,1,6320,79.00,Europe,PayPal
209,10210,July,7/28/2024,Sports,Bose SoundLink Color Bluetooth Speaker II,1,10320,129.00,Asia,Credit Card
210,10211,July,7/29/2024,Electronics,Canon EOS Rebel T7i DSLR Camera,1,59999,749.99,North America,Credit Card
211,10212,July,7/30/2024,Home Appliances,Keurig K-Elite Coffee Maker,2,13599,339.98,Europe,PayPal
212,10213,July,7/31/2024,Clothing,Uniqlo Airism Seamless Boxer Briefs,4,792,39.60,Asia,Debit Card

**Task 7:**

Filter the dataframe

For the Month - "July"

and TotalRevenue less than 350

Sort the Filtered dataframe  by arranging

"TotalRevenue" column in descending order

In [ ]:
salesdata.query('Month=="July" and TotalRevenue<350').sort_values("TotalRevenue",ascending=False)

,TransactionID,Month,Date,ProductCategory,ProductName,UnitsSold,UnitPrice,TotalRevenue,Region,PaymentMethod
211,10212,July,7/30/2024,Home Appliances,Keurig K-Elite Coffee Maker,2,13599,339.98,Europe,PayPal
204,10205,July,7/23/2024,Electronics,Samsung Galaxy Watch 4,1,23999,299.99,North America,Credit Card
192,10193,July,7/11/2024,Electronics,Logitech G Pro X Wireless Gaming Headset,1,15999,199.99,North America,Credit Card
193,10194,July,7/12/2024,Home Appliances,Breville Smart Coffee Grinder Pro,1,15996,199.95,Europe,PayPal
206,10207,July,7/25/2024,Clothing,Lululemon Wunder Under High-Rise Leggings,2,7840,196.00,Asia,Debit Card
184,10185,July,7/3/2024,Beauty Products,La Mer Crème de la Mer Moisturizer,1,15200,190.00,Europe,PayPal
182,10183,July,7/1/2024,Clothing,Levi's 511 Slim Fit Jeans,3,4799,179.97,Asia,Debit Card
200,10201,July,7/19/2024,Clothing,Gap 1969 Original Fit Jeans,3,4799,179.97,Asia,Debit Card
191,10192,July,7/10/2024,Sports,TRX All-in-One Suspension Training System,1,13596,169.95,Asia,Credit Card
188,10189,July,7/7/2024,Clothing,Nike Dri-FIT Training Shorts,4,2799,139.96,Asia,Debit Card
209,10210,July,7/28/2024,Sports,Bose SoundLink Color Bluetooth Speaker II,1,10320,129.00,Asia,Credit Card
196,10197,July,7/15/2024,Beauty Products,Tom Ford Black Orchid Perfume,1,10000,125.00,Europe,PayPal
199,10200,July,7/18/2024,Home Appliances,Instant Pot Duo Nova,1,7996,99.95,Europe,PayPal
208,10209,July,7/27/2024,Beauty Products,Caudalie Vinoperfect Radiance Serum,1,6320,79.00,Europe,PayPal
202,10203,July,7/21/2024,Beauty Products,Dr. Jart+ Cicapair Tiger Grass Color Correctin...,1,4160,52.00,Europe,PayPal
207,10208,July,7/26/2024,Books,The Great Alone by Kristin Hannah,3,1359,50.97,North America,Credit Card
212,10213,July,7/31/2024,Clothing,Uniqlo Airism Seamless Boxer Briefs,4,792,39.60,Asia,Debit Card
189,10190,July,7/8/2024,Books,The Catcher in the Rye by J.D. Salinger,3,879,32.97,North America,Credit Card
201,10202,July,7/20/2024,Books,The Goldfinch by Donna Tartt,2,1199,29.98,North America,Credit Card
183,10184,July,7/2/2024,Books,The Martian by Andy Weir,2,1039,25.98,North America,Credit Card
195,10196,July,7/14/2024,Books,The Road by Cormac McCarthy,2,959,23.98,North America,Credit Card
190,10191,July,7/9/2024,Beauty Products,Glossier Cloud Paint,1,1440,18.00,Europe,PayPal

**Task 8:**

Filter the dataframe  for

For the Month - "Aug"

and TotalRevenue greater than 400

Sort the dataframe  by arranging

"TotalRevenue" column in ascending order

Retrieve only TotalRevenue Column

In [ ]:
salesdata.query('Month=="Aug" and TotalRevenue > 400').sort_values("TotalRevenue",ascending = True)["TotalRevenue"]

217     449.99
223     459.98
229     599.00
221     599.99
216    2399.00
Name: TotalRevenue, dtype: float64

**Task 9:**

Filter the dataframe  for

For the Month - "Aug"

and TotalRevenue less than Average TotalRevenue

Sort the dataframe  by arranging

TotalRevenue column in descending order

Retrieve only "ProductName" Column.

In [ ]:
salesdata.query('Month=="Aug" and TotalRevenue < TotalRevenue.mean()').sort_values("TotalRevenue",ascending=False)["ProductName"]

221                               Garmin Forerunner 945
229                                Anova Precision Oven
223            Philips Sonicare DiamondClean Toothbrush
217                                iRobot Braava Jet M6
215                               YETI Tundra 65 Cooler
227                                         Fitbit Luxe
234         Bose QuietComfort 35 II Wireless Headphones
236                           Nike Air Force 1 Sneakers
230                     Adidas Originals Trefoil Hoodie
222                           Amazon Echo Dot (4th Gen)
228                             Google Nest Wifi Router
235     Nespresso Vertuo Next Coffee and Espresso Maker
218                       Champion Reverse Weave Hoodie
233             Hydro Flask Standard Mouth Water Bottle
224       Old Navy Mid-Rise Rockstar Super Skinny Jeans
225              The Silent Patient by Alex Michaelides
239                          Yeti Rambler 20 oz Tumbler
214                   L'Occitane Shea Butter Hand Cream
238                Sunday Riley Luna Sleeping Night Oil
237              The Handmaid's Tale by Margaret Atwood
213    The Girl with the Dragon Tattoo by Stieg Larsson
220                          Tarte Shape Tape Concealer
219                   The Nightingale by Kristin Hannah
232                           Fresh Sugar Lip Treatment
231                               Dune by Frank Herbert
226            The Ordinary Caffeine Solution 5% + EGCG
Name: ProductName, dtype: object

**Task 10:**

Filter the dataframe  for

Region - "North America" and "Europe"

Month - "July"

TotalRevenue greater than 350

Sort the Filtered dataframe  by arranging

"Region" column in descending order

then "ProductName" column in ascending order.

Retrieve only "ProductName" Column.

In [ ]:
salesdata.query('Region==["North America","Europe"]and Month==["July"] and TotalRevenue >350 ').sort_values(["Region","ProductName"],ascending=[False,True])["ProductName"]

198                        Apple TV 4K
210    Canon EOS Rebel T7i DSLR Camera
186                Sonos Beam Soundbar
187             Anova Precision Cooker
205             KitchenAid Stand Mixer
Name: ProductName, dtype: object

**Task 11:**

Store the user input for the month in the variable named as "Input_Month". Text to be shown to the user: "Enter the Month Name : "

Filter the sales dataframe for

Region - "Asia" and "Europe" and Month - 'To be taken from user input' and store the resultant data in the "Sales1" dataframe.

Print the Sales1 dataframe

At the end the user input should be-

Month (Input_Month) - Enter the Month Name : Feb

In [ ]:
Input_Month=  input("Enter the Month Name: ")
Sales1=salesdata.query('Region==["Asia","Europe"]and Month==@Input_Month')
Sales1

Enter the Month Name: Feb

,TransactionID,Month,Date,ProductCategory,ProductName,UnitsSold,UnitPrice,TotalRevenue,Region,PaymentMethod
31,10032,Feb,2/1/2024,Home Appliances,Instant Pot Duo,3,7199,269.97,Europe,PayPal
32,10033,Feb,2/2/2024,Clothing,Under Armour HeatGear T-Shirt,5,2399,149.95,Asia,Debit Card
34,10035,Feb,2/4/2024,Beauty Products,L'Oreal Revitalift Serum,2,3199,79.98,Europe,PayPal
35,10036,Feb,2/5/2024,Sports,Peloton Bike,1,151600,1895.00,Asia,Credit Card
37,10038,Feb,2/7/2024,Home Appliances,Roomba i7+,2,63999,1599.98,Europe,PayPal
38,10039,Feb,2/8/2024,Clothing,Columbia Fleece Jacket,4,4799,239.96,Asia,Debit Card
40,10041,Feb,2/10/2024,Beauty Products,Estee Lauder Advanced Night Repair,1,8400,105.00,Europe,PayPal
41,10042,Feb,2/11/2024,Sports,Fitbit Charge 5,2,10399,259.98,Asia,Credit Card
43,10044,Feb,2/13/2024,Home Appliances,Nespresso VertuoPlus,1,15999,199.99,Europe,PayPal
44,10045,Feb,2/14/2024,Clothing,Patagonia Better Sweater,2,11199,279.98,Asia,Debit Card
46,10047,Feb,2/16/2024,Beauty Products,Clinique Moisture Surge,1,4160,52.00,Europe,PayPal
47,10048,Feb,2/17/2024,Sports,Yeti Rambler Tumbler,6,3199,239.94,Asia,Credit Card
49,10050,Feb,2/19/2024,Home Appliances,Breville Smart Oven,1,23999,299.99,Europe,PayPal
50,10051,Feb,2/20/2024,Clothing,Ray-Ban Aviator Sunglasses,3,12399,464.97,Asia,Debit Card
52,10053,Feb,2/22/2024,Beauty Products,Shiseido Ultimate Sun Protector,1,3920,49.00,Europe,PayPal
53,10054,Feb,2/23/2024,Sports,Titleist Pro V1 Golf Balls,5,3999,249.95,Asia,Credit Card
55,10056,Feb,2/25/2024,Home Appliances,KitchenAid Artisan Stand Mixer,1,39999,499.99,Europe,PayPal
56,10057,Feb,2/26/2024,Clothing,Calvin Klein Boxer Briefs,5,2399,149.95,Asia,Debit Card
58,10059,Feb,2/28/2024,Beauty Products,Anastasia Beverly Hills Brow Wiz,2,1840,46.00,Europe,PayPal
59,10060,Feb,2/29/2024,Sports,Hyperice Hypervolt Massager,1,27920,349.00,Asia,Credit Card

**Task 12:**

Store the user input for the region in the variable named as "Input_Region". Text to be shown to the user "Enter the Region Name : "

Filter the Sales dataframe for

Month- "Jan" and "Feb"

and TotalRevenue greater than 1000

and Region to be taken from user input. Store the resultant data in "Sales2" dataframe.

Sort the "Sales2" dataframe by arranging

"UnitsSold" column in descending order

At the end the user input should be-

Region (Input_Region) - Enter the name of Region: 'Europe'

In [ ]:
Input_Region=input("Enter the Region Name:")
Sales2=salesdata.query('Month==["Jan","Feb"]and TotalRevenue>1000 and Region==@Input_Region')
Sales2.sort_values('UnitsSold',ascending=False)
Sales2

Enter the Region Name:Europe

,TransactionID,Month,Date,ProductCategory,ProductName,UnitsSold,UnitPrice,TotalRevenue,Region,PaymentMethod
7,10008,Jan,1/8/2024,Home Appliances,Blueair Classic 480i,2,47999,1199.98,Europe,PayPal
37,10038,Feb,2/7/2024,Home Appliances,Roomba i7+,2,63999,1599.98,Europe,PayPal

**Task 13:**

Store the user input for the month in the variable named as "Input_Month1". Text to be shown to the user "Enter the Month Name : "

Store the user input for the ProductCategory in the variable named as "Input_ProductCategory". Text to be shown to the user "Enter the Category Name : "

Filter the sales dataframe for Month to be taken from user input and Product Category to be taken from user input. Store the resultant data in "Sales3" dataframe.

Sort the "Sales3" by arranging

"TotalRevenue column in descending order

At the end the user input should be-

Month (Input_Month1) - Enter the name of Month: July

ProductCategory (Input_ProductCategory) - Enter the name of ProductCategory: Electronics

In [ ]:
Input_Month1=input("Enter the Month Name: ")
Input_ProductCategory=input("Enter the Category Name : ")
Sales3=salesdata.query('Month==@Input_Month1 and ProductCategory==@Input_ProductCategory')
Sales3=Sales3.sort_values("TotalRevenue",ascending=False)
Sales3

Enter the Month Name: July
Enter the Category Name : Electronics

,TransactionID,Month,Date,ProductCategory,ProductName,UnitsSold,UnitPrice,TotalRevenue,Region,PaymentMethod
210,10211,July,7/29/2024,Electronics,Canon EOS Rebel T7i DSLR Camera,1,59999,749.99,North America,Credit Card
186,10187,July,7/5/2024,Electronics,Sonos Beam Soundbar,1,31920,399.00,North America,Credit Card
198,10199,July,7/17/2024,Electronics,Apple TV 4K,2,14320,358.00,North America,Credit Card
204,10205,July,7/23/2024,Electronics,Samsung Galaxy Watch 4,1,23999,299.99,North America,Credit Card
192,10193,July,7/11/2024,Electronics,Logitech G Pro X Wireless Gaming Headset,1,15999,199.99,North America,Credit Card

**Task 14:**

Store the user input for the region in the variable named as "Input_Region3". Text to be shown to the user "Enter the Region Name : "

Store the user input for the ProductCategory in the variable named as "Input_ProductCategory1". Text to be shown to the user "Enter the ProductCategory Name : " Filter the sales dataframe for Region to be taken from user input and ProductCategory to be taken from user input. Store the resultant data in "Sales4" dataframe.

Create a pivot table using the Sales4 dataframe named pivot_2 to show the ProductName-wise total revenue and total unit sold for each of the ProductCategory. Use index as ProductName, columns as ProductCategory and values as TotalRevenue and UnitsSold. Print this pivot table. This will show the data for the ProductCategory and Region selected by the user.

At the end the user input should be-

Region (Input_Region3) - Enter the region name : Asia

ProductCategory (Input_ProductCategory1) - Enter the ProductCategory name : Clothing

In [ ]:
Input_Region3=input("Enter the Region Name : ")
Input_ProductCategory1=input("Enter the ProductCategory Name : " )
Sales4=salesdata.query('Region==@Input_Region3 and ProductCategory==@Input_ProductCategory1')
Pivot_2= pd.pivot_table(Sales4,index="ProductName",columns="Region",values=["TotalRevenue", "UnitsSold"],aggfunc={"UnitsSold":["sum"],"TotalRevenue":["sum"]})
Pivot_2

Enter the Region Name : Asia
Enter the ProductCategory Name : Clothing

                                              TotalRevenue UnitsSold
                                                       sum       sum
Region                                                Asia      Asia
ProductName
Adidas 3-Stripes Shorts                             149.95         5
Adidas Essential Track Pants                        134.97         3
Adidas Originals Superstar Sneakers                 319.96         4
Adidas Originals Trefoil Hoodie                     259.96         4
Adidas Ultraboost Running Shoes                     359.98         2
Adidas Ultraboost Shoes                             359.98         2
Calvin Klein Boxer Briefs                           149.95         5
Champion Reverse Weave Hoodie                       149.97         3
Columbia Fleece Jacket                              239.96         4
Forever 21 Graphic Tee                               64.95         5
Gap 1969 Original Fit Jeans                         179.97         3
Gap Crewneck Sweatshirt                             139.96         4
Gap Essential Crewneck T-Shirt                      119.94         6
Gap High Rise Skinny Jeans                          149.97         3
H&M Slim Fit Jeans                                  119.97         3
Hanes ComfortSoft T-Shirt                            99.90        10
Levi's 501 Jeans                                    209.97         3
Levi's 511 Slim Fit Jeans                           179.97         3
Levi's Sherpa Trucker Jacket                        196.00         2
Levi's Trucker Jacket                               179.98         2
Lululemon Align Leggings                            294.00         3
Lululemon Wunder Under High-Rise Leggings           196.00         2
Nike Air Force 1                                    539.94         6
Nike Air Force 1 Sneakers                           270.00         3
Nike Dri-FIT Training Shorts                        139.96         4
Nike Sportswear Club Fleece Hoodie                  164.97         3
Nike Tempo Running Shorts                           104.97         3
North Face Down Jacket                              499.98         2
Old Navy Mid-Rise Rockstar Super Skinny Jeans        89.98         2
Old Navy Relaxed-Fit T-Shirt                         59.96         4
Patagonia Better Sweater                            279.98         2
Puma Suede Classic Sneakers                         239.96         4
Ray-Ban Aviator Sunglasses                          464.97         3
Tommy Hilfiger Polo Shirt                           249.95         5
Under Armour HeatGear T-Shirt                       149.95         5
Under Armour Tech 2.0 T-Shirt                        99.96         4
Uniqlo Airism Mesh Boxer Briefs                      59.60         4
Uniqlo Airism Seamless Boxer Briefs                  39.60         4
Uniqlo Ultra Light Down Jacket                      239.97         3
Zara Summer Dress                                   179.97         3

**Submission of exercise:**


*   Once you have completed all the tasks in the colab file, please provide editor’s access so that evaluators can provide comments if necessary.

*   Once done, copy the link of the colab file and paste it in the box given below. Click on the Submit button to submit your exercise.