<a href="https://colab.research.google.com/github/Vinothini12b/Python-Data-Analysis-Projects/blob/main/Vinothini_GolfMotorCompany.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# GolfMotorCompany 9.1

***`Task 1: Import Pandas Library and create a dataframe named “tyresales” from a given URL and then print it. URL - https://raw.githubusercontent.com/Invact-Abhay/DO9/main/tyresale.csv`***

In [ ]:
import pandas as pd
tyresales=pd.read_csv("https://raw.githubusercontent.com/Invact-Abhay/DO9/main/tyresale.csv")
tyresales

,OrderID,ProductName,ProductCategory,CustomerName,CustomerCategory,Month,Zone,UnitsSold,PerUnitPrice,SalesCommissionPaid
0,1,Car Tyres Rapid,Car,@alpha motors pvt ltd,Big,January,East,77,131.22,532.59
1,2,Car Tyres Rapid,Car,@ alpha motors pvt ltd,Big,January,South,16,131.37,121.74
2,3,Car Tyres Rapid,Car,@ alpha motors pvt ltd,Big,January,West,35,197.60,384.94
3,4,Car Tyres Rapid,Car,@BRAVO AUTO CORP,Medium,January,East,74,111.72,437.32
4,5,Car Tyres Rapid,Car,@ BRAVO AUTO CORP,Medium,January,Central,30,191.15,307.06
...,...,...,...,...,...,...,...,...,...,...
1431,1432,Two-wheeler Tyres Cruiser,Two-wheeler,@ INDIA TYRES CO,Medium,June,Central,50,96.53,266.44
1432,1433,Two-wheeler Tyres Cruiser,Two-wheeler,@ india tyres co,Medium,June,North,41,145.93,334.47
1433,1434,Two-wheeler Tyres Cruiser,Two-wheeler,@juliet automotive pvt ltd,Small,June,North,18,82.01,80.93
1434,1435,Two-wheeler Tyres Cruiser,Two-wheeler,@ JULIET AUTOMOTIVE PVT LTD,Small,June,Central,75,83.58,363.91
1435,1436,Two-wheeler Tyres Cruiser,Two-wheeler,@JULIET AUTOMOTIVE PVT LTD,Small,June,East,39,121.33,255.87

***`Task 2: Clean the customer name by using strip and title function and removing '@' and any space between the name and give name to this column - ‘CustomerNameClean’ then retrieve ‘CustomerNameClean’ in Alphabetical order. ‘CustomerNameClean’ should look like this - AlphaMotorsPvtLtd.`***

In [ ]:
tyresales["CustomerNameClean"]=tyresales["CustomerName"].str.strip()\
                                                        .str.replace('@','')\
                                                        .str.title()\
                                                        .str.replace(' ','')+'.'
tyresales.sort_values("CustomerNameClean",ascending=True)

,OrderID,ProductName,ProductCategory,CustomerName,CustomerCategory,Month,Zone,UnitsSold,PerUnitPrice,SalesCommissionPaid,CustomerNameClean
0,1,Car Tyres Rapid,Car,@alpha motors pvt ltd,Big,January,East,77,131.22,532.59,AlphaMotorsPvtLtd.
856,857,Cycle Tyres Rider,Cycle,@ALPHA MOTORS PVT LTD,Big,April,West,35,96.19,172.03,AlphaMotorsPvtLtd.
1169,1170,Two-wheeler Tyres Cruiser,Two-wheeler,@ALPHA MOTORS PVT LTD,Big,May,North,22,99.78,131.39,AlphaMotorsPvtLtd.
327,328,Truck Tyres LongHaul,Truck,@ALPHA MOTORS PVT LTD,Big,February,South,69,283.24,1326.68,AlphaMotorsPvtLtd.
328,329,Truck Tyres LongHaul,Truck,@ Alpha Motors Pvt Ltd,Big,February,South,23,248.91,397.81,AlphaMotorsPvtLtd.
...,...,...,...,...,...,...,...,...,...,...,...
1130,1131,Cycle Tyres Rider,Cycle,@Juliet Automotive Pvt Ltd,Small,May,West,87,74.67,411.94,JulietAutomotivePvtLtd.
303,304,Car Tyres Gripper,Car,@Juliet Automotive Pvt Ltd,Small,February,Central,58,192.78,584.37,JulietAutomotivePvtLtd.
1129,1130,Cycle Tyres Rider,Cycle,@Juliet Automotive Pvt Ltd,Small,May,West,49,62.27,193.32,JulietAutomotivePvtLtd.
353,354,Truck Tyres LongHaul,Truck,@juliet automotive pvt ltd,Small,February,Central,81,367.16,1970.48,JulietAutomotivePvtLtd.
1435,1436,Two-wheeler Tyres Cruiser,Two-wheeler,@JULIET AUTOMOTIVE PVT LTD,Small,June,East,39,121.33,255.87,JulietAutomotivePvtLtd.

***`Task 3: Calculate the Sales for every customer by calculating Sales column`***

In [ ]:
tyresales["Sales"]=tyresales["UnitsSold"]*tyresales["PerUnitPrice"]
tyresales

,OrderID,ProductName,ProductCategory,CustomerName,CustomerCategory,Month,Zone,UnitsSold,PerUnitPrice,SalesCommissionPaid,CustomerNameClean,Sales
0,1,Car Tyres Rapid,Car,@alpha motors pvt ltd,Big,January,East,77,131.22,532.59,AlphaMotorsPvtLtd.,10103.94
497,498,Car Tyres Gripper,Car,@ ALPHA MOTORS PVT LTD,Big,March,North,80,112.91,528.56,AlphaMotorsPvtLtd.,9032.80
520,521,Truck Tyres HeavyDuty,Truck,@ ALPHA MOTORS PVT LTD,Big,March,South,48,361.30,1119.21,AlphaMotorsPvtLtd.,17342.40
521,522,Truck Tyres HeavyDuty,Truck,@ Alpha Motors Pvt Ltd,Big,March,North,29,386.12,699.44,AlphaMotorsPvtLtd.,11197.48
522,523,Truck Tyres HeavyDuty,Truck,@ Alpha Motors Pvt Ltd,Big,March,West,80,307.03,1640.73,AlphaMotorsPvtLtd.,24562.40
...,...,...,...,...,...,...,...,...,...,...,...,...
495,496,Car Tyres Rapid,Car,@ JULIET AUTOMOTIVE PVT LTD,Small,March,West,58,112.36,332.88,JulietAutomotivePvtLtd.,6516.88
1015,1016,Car Tyres Gripper,Car,@ juliet automotive pvt ltd,Small,May,South,81,137.58,573.95,JulietAutomotivePvtLtd.,11143.98
1016,1017,Car Tyres Gripper,Car,@JULIET AUTOMOTIVE PVT LTD,Small,May,East,64,101.37,377.27,JulietAutomotivePvtLtd.,6487.68
984,985,Car Tyres Rapid,Car,@Juliet Automotive Pvt Ltd,Small,May,South,40,178.17,398.95,JulietAutomotivePvtLtd.,7126.80
1435,1436,Two-wheeler Tyres Cruiser,Two-wheeler,@JULIET AUTOMOTIVE PVT LTD,Small,June,East,39,121.33,255.87,JulietAutomotivePvtLtd.,4731.87

**`Task 4: Find the total Sales.`**

In [ ]:
TotalSales=tyresales["Sales"].sum()
TotalSales

12590076.14

***`Task 5: Take the user Input for CustomerNameClean and retrieve the data for 'Alpha Motors Pvt Ltd'.`***

In [ ]:
customer_input=input("Enter the Customer Name:")
customer_data = tyresales[tyresales['CustomerNameClean'] == customer_input]
if not customer_data.empty:
    print("Data for", customer_input)
    print(customer_data)
else:
    print("No data found for", customer_input)

Enter the Customer Name:AlphaMotorsPvtLtd.
Data for AlphaMotorsPvtLtd.
      OrderID                ProductName ProductCategory  \
0           1            Car Tyres Rapid             Car
497       498          Car Tyres Gripper             Car
520       521      Truck Tyres HeavyDuty           Truck
521       522      Truck Tyres HeavyDuty           Truck
522       523      Truck Tyres HeavyDuty           Truck
...       ...                        ...             ...
1264     1265      Truck Tyres HeavyDuty           Truck
234       235            Car Tyres Rapid             Car
235       236            Car Tyres Rapid             Car
236       237            Car Tyres Rapid             Car
206       207  Two-wheeler Tyres Cruiser     Two-wheeler

                  CustomerName CustomerCategory     Month     Zone  UnitsSold  \
0       @alpha motors pvt ltd               Big   January     East         77
497     @ ALPHA MOTORS PVT LTD              Big     March    North         80
520    @ ALPHA MOTORS PVT LTD               Big     March    South         48
521    @ Alpha Motors Pvt Ltd               Big     March    North         29
522     @ Alpha Motors Pvt Ltd              Big     March     West         80
...                        ...              ...       ...      ...        ...
1264    @ alpha motors pvt ltd              Big      June    South         55
234     @ALPHA MOTORS PVT LTD               Big  February  Central         46
235      @ALPHA MOTORS PVT LTD              Big  February     West         33
236      @ALPHA MOTORS PVT LTD              Big  February  Central         23
206     @Alpha Motors Pvt Ltd               Big   January    South         43

      PerUnitPrice  SalesCommissionPaid   CustomerNameClean     Sales  \
0           131.22               532.59  AlphaMotorsPvtLtd.  10103.94
497         112.91               528.56  AlphaMotorsPvtLtd.   9032.80
520         361.30              1119.21  AlphaMotorsPvtLtd.  17342.40
521         386.12               699.44  AlphaMotorsPvtLtd.  11197.48
522         307.03              1640.73  AlphaMotorsPvtLtd.  24562.40
...            ...                  ...                 ...       ...
1264        286.01               979.74  AlphaMotorsPvtLtd.  15730.55
234         120.64               291.71  AlphaMotorsPvtLtd.   5549.44
235         146.85               256.35  AlphaMotorsPvtLtd.   4846.05
236         155.74               211.96  AlphaMotorsPvtLtd.   3582.02
206          89.80               202.72  AlphaMotorsPvtLtd.   3861.40

       TotalSales
0     12590076.14
497   12590076.14
520   12590076.14
521   12590076.14
522   12590076.14
...           ...
1264  12590076.14
234   12590076.14
235   12590076.14
236   12590076.14
206   12590076.14

[145 rows x 13 columns]

***`Task 6: Find the average SalesCommission% by calculating the SalesCommission% column.SalesCommission% = SalesCommissionPaid / Sales * 100`***

In [ ]:
tyresales["SalesCommission%"]=(tyresales["SalesCommissionPaid"] / tyresales["Sales"] )* 100
average_sales_commission = tyresales["SalesCommission%"].mean()
average_sales_commission

5.862378385232829

**`Task 7: Take the user Input for Zone and Find the average SalesCommission% of Central Zone.`**

In [ ]:
zone_input = input("Enter the Zone: ")
average_sales_commission_zone = tyresales[tyresales['Zone'] == zone_input]['SalesCommission%'].mean()
if average_sales_commission_zone:
    print(f"Average Sales Commission% for {zone_input} Zone:", average_sales_commission_zone)
else:
    print(f"No data found for {zone_input} Zone.")

Enter the Zone: Central
Average Sales Commission% for Central Zone: 5.872509602190537

***`Task 8: Sort the file as per Sales Transaction in descending order and show the top five transactions.`***

In [ ]:
tyresales.sort_values('Sales',ascending=False).head()

,OrderID,ProductName,ProductCategory,CustomerName,CustomerCategory,Month,Zone,UnitsSold,PerUnitPrice,SalesCommissionPaid,CustomerNameClean,Sales,TotalSales,SalesCommission%
1064,1065,Truck Tyres LongHaul,Truck,@Echo Motors Ltd,Medium,May,North,99,399.81,2649.47,EchoMotorsLtd.,39581.19,12590076.14,6.693760
80,81,Truck Tyres HeavyDuty,Truck,@hotel wheels inc,Medium,January,West,95,394.51,2506.80,HotelWheelsInc.,37478.45,12590076.14,6.688644
73,74,Truck Tyres HeavyDuty,Truck,@echo motors ltd,Medium,January,Central,99,376.72,2291.93,EchoMotorsLtd.,37295.28,12590076.14,6.145362
1285,1286,Truck Tyres HeavyDuty,Truck,@ juliet automotive pvt ltd,Small,June,South,93,398.50,2443.42,JulietAutomotivePvtLtd.,37060.50,12590076.14,6.593057
524,525,Truck Tyres HeavyDuty,Truck,@Alpha Motors Pvt Ltd,Big,March,Central,93,397.28,2266.89,AlphaMotorsPvtLtd.,36947.04,12590076.14,6.135512

***`Task 9: Find the top 5 sales transactions with highest sales amount at top for ProductCategory 'Car'.`***

In [ ]:
tyresales.query('ProductCategory=="Car"').sort_values("Sales",ascending=False).head()

,OrderID,ProductName,ProductCategory,CustomerName,CustomerCategory,Month,Zone,UnitsSold,PerUnitPrice,SalesCommissionPaid,CustomerNameClean,Sales,TotalSales,SalesCommission%
264,265,Car Tyres Rapid,Car,@hotel wheels inc,Medium,February,East,98,188.20,1100.91,HotelWheelsInc.,18443.60,12590076.14,5.969062
30,31,Car Tyres Rapid,Car,@ INDIA TYRES CO,Medium,January,East,90,196.56,930.94,IndiaTyresCo.,17690.40,12590076.14,5.262402
1254,1255,Car Tyres Gripper,Car,@ HOTEL WHEELS INC,Medium,June,West,97,178.35,894.35,HotelWheelsInc.,17299.95,12590076.14,5.169668
1234,1235,Car Tyres Gripper,Car,@Alpha Motors Pvt Ltd,Big,June,South,100,170.39,893.32,AlphaMotorsPvtLtd.,17039.00,12590076.14,5.242796
18,19,Car Tyres Rapid,Car,@Echo Motors Ltd,Medium,January,West,92,178.49,981.68,EchoMotorsLtd.,16421.08,12590076.14,5.978170

***`Task 10: Find the Name of top 5 'CustomerNameClean' on basis of amount in a single sales transaction in the month of June.`***

In [ ]:
june_transactions = tyresales[tyresales['Month'] == 'June']
sorted_june_transactions = june_transactions.sort_values(by='Sales', ascending=False)
top_5_customers_june = sorted_june_transactions[['CustomerNameClean', 'Sales']].head()
top_5_customers_june

            CustomerNameClean     Sales
1285  JulietAutomotivePvtLtd.  37060.50
1282          HotelWheelsInc.  34762.47
1283            IndiaTyresCo.  32399.64
1320            IndiaTyresCo.  32225.04
1312        GolfMotorCompany.  28507.08

***`Task 11: Take the user Input for Zone. Show the total sales of the Zone which is being input by the user. Put the Zone input - West.`***

In [ ]:
zone_input = input("Enter the Zone: ")
total_sales_zone = tyresales[tyresales['Zone'] == zone_input]['Sales'].sum()
if total_sales_zone > 0:
    print(f"Total Sales for {zone_input} Zone:", total_sales_zone)
else:
    print(f"No sales data found for {zone_input} Zone.")

Enter the Zone: West
Total Sales for West Zone: 2565909.16

***`Task 12: List all the sales transactions where PerUnitPrice is more than 398 in descending order based on sales.`***

In [ ]:
tyresales.query("PerUnitPrice>398").sort_values("Sales",ascending =False)

,OrderID,ProductName,ProductCategory,CustomerName,CustomerCategory,Month,Zone,UnitsSold,PerUnitPrice,SalesCommissionPaid,CustomerNameClean,Sales,TotalSales,SalesCommission%
1064,1065,Truck Tyres LongHaul,Truck,@Echo Motors Ltd,Medium,May,North,99,399.81,2649.47,EchoMotorsLtd.,39581.19,12590076.14,6.693760
1285,1286,Truck Tyres HeavyDuty,Truck,@ juliet automotive pvt ltd,Small,June,South,93,398.50,2443.42,JulietAutomotivePvtLtd.,37060.50,12590076.14,6.593057
343,344,Truck Tyres LongHaul,Truck,@ Hotel Wheels Inc,Medium,February,Central,50,398.29,1325.91,HotelWheelsInc.,19914.50,12590076.14,6.658013
809,810,Truck Tyres LongHaul,Truck,@Charlie Transport Ltd,Big,April,North,33,399.98,879.99,CharlieTransportLtd.,13199.34,12590076.14,6.666924

***`Task 13: Find the average SalesCommission% of ProductCategory 'Truck'.`***

In [ ]:
tyresales.query('ProductCategory=="Truck"')["SalesCommission%"].mean()

6.502232102980405

***`Task 14: Find the average SalesCommission% of ProductCategory 'Two-wheeler'.`***

In [ ]:
tyresales.query('ProductCategory=="Two-wheeler"')["SalesCommission%"].mean()

5.507832631622494

***`Task 15: Find the Maximum Sales of 'Medium' CustomerCategory.`***

In [ ]:
tyresales.query('CustomerCategory=="Medium"')["Sales"].max()

39581.19

***`Task 16: Take the user Input for ProductName. Find the Maximum UnitsSold for the specified ProductName.`***

In [ ]:
product_input = input("Enter the Product Name: ")
max_units_sold = tyresales[tyresales['ProductName'] == product_input]['UnitsSold'].max()

if max_units_sold is not None:
    print(f"Maximum Units Sold for '{product_input}':", max_units_sold)
else:
    print(f"No sales data found for the product '{product_input}'.")

Enter the Product Name: Truck Tyres LongHaul
Maximum Units Sold for 'Truck Tyres LongHaul': 100

***`Task 17: Take the user Input for Month. Find the Average SalesCommission% for the specified Month.  Enter the Month input - 'May'`***

In [ ]:
month_input = input("Enter the Month: ")

average_sales_commission = tyresales[tyresales['Month'] == month_input]['SalesCommission%'].mean()

if not pd.isna(average_sales_commission):
    print(f"Average SalesCommission% for {month_input}: {average_sales_commission}")
else:
    print(f"No sales data found for the month '{month_input}'.")

Enter the Month: May
Average SalesCommission% for May: 5.832810631043766

***`Task 18: Find the total number of transactions`***

In [ ]:
tyresales['Sales'].count()

1436

In [ ]:
tyresales.shape[0]

1436

***`Task 19: Take the user input for Product Category. Find the minimum sales commission paid for the specified product category. Enter ProductCategory- Truck`***

In [ ]:
product_category_input = input("Enter the Product Category: ")

minimum_sales_commission = tyresales[tyresales['ProductCategory'] == product_category_input]['SalesCommissionPaid'].min()

if minimum_sales_commission is not None:
    print(f"Minimum Sales Commission Paid for '{product_category_input}':", minimum_sales_commission)
else:
    print(f"No sales data found for the product category '{product_category_input}'.")

Enter the Product Category: Truck
Minimum Sales Commission Paid for 'Truck': 144.08

***`Task 20: Find the average per unit price of the north zone.`***

In [ ]:
tyresales.query('Zone=="North"')["PerUnitPrice"].mean()

159.60303571428574

***`Task 21: Take a user input for Month. Find the number of transactions (OrderID) in the particular month. Take Month- April.`***

In [ ]:
month_input = input("Enter the Month: ")

number_of_transactions = tyresales[tyresales['Month'] == month_input]['OrderID'].count()

print(f"Number of transactions in {month_input}: {number_of_transactions}")

Enter the Month: April
Number of transactions in April: 245

***`Task 22: Find the average sales of all transactions where Units sold is 99.`***

In [ ]:
tyresales.query('UnitsSold==99')["Sales"].mean()

18956.52

***`Task 23: Show the top 5 transactions showing lowest Units sold on the top for product category Car.`***

In [ ]:
tyresales.query("ProductCategory=='Car'").sort_values('UnitsSold',ascending=True).head()

,OrderID,ProductName,ProductCategory,CustomerName,CustomerCategory,Month,Zone,UnitsSold,PerUnitPrice,SalesCommissionPaid,CustomerNameClean,Sales,TotalSales,SalesCommission%
1012,1013,Car Tyres Gripper,Car,@ india tyres co,Medium,May,North,10,153.36,91.51,IndiaTyresCo.,1533.60,12590076.14,5.967006
268,269,Car Tyres Rapid,Car,@hotel wheels inc,Medium,February,East,10,128.71,73.81,HotelWheelsInc.,1287.10,12590076.14,5.734597
479,480,Car Tyres Rapid,Car,@ECHO MOTORS LTD,Medium,March,North,10,128.50,66.48,EchoMotorsLtd.,1285.00,12590076.14,5.173541
1222,1223,Car Tyres Rapid,Car,@GOLF MOTOR COMPANY,Small,June,South,10,117.91,61.40,GolfMotorCompany.,1179.10,12590076.14,5.207362
242,243,Car Tyres Rapid,Car,@ Bravo Auto Corp,Medium,February,North,11,140.28,91.28,BravoAutoCorp.,1543.08,12590076.14,5.915442